django/cardapiododia/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ondealmocar.views.home', name='home'),
    # url(r'^ondealmocar/', include('ondealmocar.foo.urls')),

    # Django Admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
    #configuracao para ser possivel acessar os arquivos em /media/
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', 
		{'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),    
    
)

urlpatterns += patterns('',
    url(r'', include('votacao.urls')),
)

django/votacao/urls.py
from django.conf.urls import patterns, url

from .views import home, criar_votacao, opcoes_votacao, novo_voto, sobre, VotoListView

urlpatterns = patterns('votacao.views',

    #votacao    
    url(r'^votacao/nova', criar_votacao, name='url_criar_votacao'),
    
    url(r'^votacao/novo_voto/(\d+)', novo_voto, name='url_novo_voto'),
    
    url(r'^votacao/resumo/(\d+)', VotoListView.as_view(), name='url_votacao_resumo'),
    
    url(r'^votacao/(\d+)', opcoes_votacao, name='url_opcoes_votacao'),
    
    url(r'^votacao/sobre', sobre, name='url_sobre'),

	url(r'^votacao/', home, name='url_home'),
    
)

django/votacao/models.py
# coding=utf-8

from datetime import datetime

from django.db import models

DIAS_DA_SEMANA = [
    ('Monday', u'Segunda-Feira'),
    ('Tuesday', u'Terça-Feira'),
    ('Wednesday', u'Quarta-Feira'),
    ('Thursday', u'Quinta-Feira'),
    ('Friday', u'Sexta-Feira'),
    ('Saturday', u'Sábado'),
    ('Sunday', u'Domingo'),
]

class Restaurante(models.Model):
    nome = models.CharField(max_length=128, db_index=True)
    logotipo = models.FileField(upload_to='logotipo')
    cardapioGeral = models.FileField(upload_to='cardapio')
    
    def __unicode__(self):
        return self.nome  
        
class Cardapio(models.Model):
    restaurante = models.ForeignKey(Restaurante)
    dia = models.CharField(max_length=32, choices=DIAS_DA_SEMANA)
    cardapioDia = models.FileField(upload_to='cardapio')

    def __unicode__(self):
        return self.dia

class Votacao(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    nome = models.CharField(max_length=64)
    dataDoAlmoco = models.DateTimeField(u'Data do almoço')
    diaDaSemana = models.CharField(max_length=32, choices=DIAS_DA_SEMANA, blank=True)
    encerrada = models.BooleanField(default=False)
	
    def __unicode__(self):
        return self.nome
        
class Voto(models.Model):
    nome = models.CharField(max_length=64)
    restaurante = models.ForeignKey(Restaurante)
    votacao = models.ForeignKey(Votacao)
    
    def __unicode__(self):
        return self.nome

django/votacao/forms.py
#coding=utf-8

from django.forms import ModelForm, ValidationError

from datetime import date, datetime

from .models import Votacao

from django import forms


class VotacaoModelForm(ModelForm):
    
	dataDoAlmoco = forms.DateTimeField(widget=forms.TextInput(attrs={'data-datepicker':'datepicker'}))
	
	class Meta:
		model = Votacao
        
	def clean_diaDaSemana(self):
		""" atribui o diaDaSemana
			conforme o dataDoAlmoco especificado
		"""
		
		if 'dataDoAlmoco' not in self.cleaned_data:
			raise forms.ValidationError('É necessario preencher a data')
		
		dado = self.cleaned_data['dataDoAlmoco']
		
		return dado.strftime('%A')
		
	#def clean(self):
	#	dataDoAlmoco = self.cleaned_data.get('dataDoAlmoco')
	#	nome = self.cleaned_data.get('nome')
		
		#print '=============>', dataDoAlmoco
		#if dataDoAlmoco is None:
	#		raise forms.ValidationError('É necessario preencher a data')
			
	#	if nome is not None:
	#		raise forms.ValidationError('É necessario preencher nome')
			
		
			
	#	return self.cleaned_data
			
		
		

django/votacao/views.py
# Create your views here.
from django.shortcuts import render

from django import forms
from django.http import HttpResponseRedirect, HttpResponse
from django.forms.widgets import HiddenInput
from django.shortcuts import render, render_to_response, get_object_or_404
from django.views.generic import ListView

from django.db.models import Count

from datetime import date, datetime, time

from .models import Votacao, Cardapio, Voto, Restaurante
from .forms import VotacaoModelForm

def home(request):
	menuId = 0
	template_name = 'votacao/home.html'
	listVotacao = Votacao.objects.filter(data__gte=date.today())[:10]
	
	return render(request, template_name, {'menuId':menuId, 'listVotacao':listVotacao })

def sobre(request):
	return render_to_response("votacao/sobre.html")    
    

            
def criar_votacao(request):
	
	menuId = 1

	if request.POST:
		form = VotacaoModelForm(request.POST)
        
		if form.is_valid():
			votacao = form.save()
			return HttpResponseRedirect('/votacao/' + str(votacao.id))
	else:

		hoje = date.today()
		meiodia = datetime.combine(hoje, time(12, 00))
		nova_votacao = Votacao(dataDoAlmoco=meiodia)
		form = VotacaoModelForm(instance=nova_votacao)

	
	form.fields['encerrada'].widget = HiddenInput()
	form.fields['diaDaSemana'].widget = HiddenInput()
	payload = {'form':form, 'menuId':menuId}
	print '-------------------->'
	print form
	print '-------------------->'
	return render(request, 'votacao/criarvotacao.html', payload) 

def opcoes_votacao(request, id_votacao):
	menuId = 1
	votacao = get_object_or_404(Votacao, pk=id_votacao)
	cardapios = Cardapio.objects.filter(dia=votacao.diaDaSemana)
	return render(request, 'votacao/opcoesvotacao.html', {'votacao': votacao, 'cardapio_list': cardapios, 'menuId':menuId})
    
def novo_voto(request, id_votacao):
    votacao_form = get_object_or_404(Votacao, pk=id_votacao)
    restaurante_id = request.POST.get('id_restaurante', None)
    restaurante_form = get_object_or_404(Restaurante, pk=restaurante_id)
    nome_form = request.POST.get('nome', '')
    
    voto = Voto(nome=nome_form, restaurante=restaurante_form, votacao=votacao_form)
    voto.save()
    return HttpResponseRedirect('/votacao/resumo/' + str(votacao_form.id))
    
class VotoListView(ListView):
    template_name='votacao/resumovotacao.html'
    
    def get_queryset(self):
        self.votacao = get_object_or_404(Votacao, pk=self.args[0])
        votacoes = Voto.objects.filter(votacao=self.votacao).values('restaurante').annotate(dcount=Count('restaurante')).order_by('-dcount')

		#TODO: como fazer o ORM do Django fazer JOIN diretamente de modo a nao gerar 1 select para cada item da listagem
        result = []
        for voto in votacoes:
			id_restaurante = voto['restaurante']
			restaurante_db = get_object_or_404(Restaurante, pk=id_restaurante)
			result.append( dict(restaurante=restaurante_db, votos=voto['dcount']) )
        
        return result
    

django/cardapiododia/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load admin_urls %}

<html>

	<head>
		<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="author" content="Roger.Camargo">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-responsive.min.css'%}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/datepicker.css'%}" />
        <!--<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-popover.css'%}" />-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/cardapioDoDia.css'%}" />

	</head>
	
    <body data-spy="scroll" data-target=".bs-docs-sidebar">
		<input type="hidden" id="menuId" value="{{ menuId }}"/>
		<div class="navbar navbar-fixed-top">
	      <div class="navbar-inner">
	        <div class="container">
	          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </a>
	          <a class="brand" href="#">Cardapio do dia</a>
	          <div class="nav-collapse">
	            <ul id="menu-superior" class="nav">
	              <li><a href="{% url url_home %}">Home</a></li>
	              <li><a href="{% url url_criar_votacao %}">Votacao</a></li>
                  <li><a href="/admin/votacao/restaurante/">Restaurantes</a></li>
	              <li><a href="{% url url_sobre %}">Sobre</a></li>
	            </ul>
	          </div><!--/.nav-collapse -->
	        </div>
	      </div>
	    </div>	
		

        <div class="jumbotron masthead">
            <div class="container">
                <br /><br /><br />
			
			{% block corpo %}
			<!-- body -->
			{% endblock %}
			
			<br /><br /><br />
			<hr>	
		    <footer>
                <ul class="masthead-links">
                  <li><a href="http://github.com/huogerac/cardapiododia">GitHub project</a></li>
                </ul>
		    </footer>			
		
            </div>
		</div>
		
		<!-- javascript -->
		<!--
			Django JQuery
		<script type="text/javascript" src="/static/admin/js/jquery.js"></script>
		<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
		-->
		<script type='text/javascript' src="{% static 'js/jquery-1.7.1.js'%}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js'%}"></script>
		<script type="text/javascript" src="{% static 'js/cardapio.js'%}"></script>
		
		{% block javascript %}
		<!--  extra javascript-->
			
		{% endblock %}
		
	</body>

</html>

django/votacao/templates/votacao/criarvotacao.html
{% extends 'base.html' %}

{% block chamada %}TESTE{% endblock %}

{% block corpo %}


    <section id="global">

        <div class="page-header">
             <h2>Nova votação</h2>
        </div>
        
        <form action="" method="post"> {% csrf_token %}
	
			{{ form.nome.label_tag }}
			{{ form.nome }}
			<span class="error_forms">{{ form.nome.errors }}</span>
			
			{{ form.dataDoAlmoco.label_tag }}
			<div>
				
				{{ form.dataDoAlmoco }} <input type="text" id="id_dataDoAlmoco_hour" />
				<span class="error_forms">{{ form.dataDoAlmoco.errors }}</span>
			</div>
		
			{{ form.diaDaSemana }}
			{{ form.encerrada }}
            
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Criar votação</button>
                <a href="{% url url_home %}" class="btn">Cancelar</a>
            </div>

        </form>

    </section>	
	
	
	

{% endblock corpo %}

{% block javascript %}
<script type="text/javascript">
	$(function(){
		$("form").submit(function(){
			var inpDate = $("#id_dataDoAlmoco");
			inpDate.val(inpDate.val().trim() + ' ' + $("#id_dataDoAlmoco_hour").val().trim());
		});
	});
</script>

{% endblock javascript %}

django/votacao/templates/votacao/home.html
{% extends 'base.html' %}

{% load static %}

{% block chamada %}TESTE{% endblock %}

{% block corpo %}

	<div align="center">
        <h1>Cardápio do dia</h1>
        <!--
        <input data-datepicker="datepicker" class="small" type="text" value="05/08/2011" />
        -->
        <p>Chega de perder tempo para decidir onde almoçar</p>
        <p><a href="{% url url_criar_votacao %}" class="btn btn-primary btn-large">Criar Votação</a></p>
        <img src="{% static 'img/cardapiododia_mapa.jpg'%}">
        
        <div id="votacoes_corrente">
			
			<h3>Votações em Andamento</h2>
        
			{% for votacao in listVotacao %}
				| <a href="/votacao/{{ votacao.id }}">{{ votacao.nome }}</a>
			{% endfor %} |
        </div>
    </div>
	
{% endblock corpo %}

{% block javascript %}
{% endblock javascript %}

django/votacao/templates/votacao/opcoesvotacao.html
{% extends 'base.html' %}

{% block chamada %}VOTACAO{% endblock %}

{% block corpo %}

    <section id="global">

        <div class="page-header">
            <h2>{{ votacao.nome }}</h2>
            <h4>{{ votacao.dataDoAlmoco }}</h4>
            <h6><a href="{% url url_opcoes_votacao votacao.id %}">Compartilhe esta URL para votação</a></h6>
        </div>
        
        
        <table align="center">
         {% for cardapio in cardapio_list %}
              <tr>
                 <td colspan="3"><h2>{{cardapio.restaurante}}</h2></td>
              </tr>
              <tr>
                <td><img width="120" src="{{ MEDIA_URL }}{{ cardapio.restaurante.logotipo }}" class="img-rounded"></td>
                <td><img width="540" src="{{ MEDIA_URL }}{{ cardapio.restaurante.cardapioGeral }}" class="img-polaroid"></td>
                <td>
                    <form action="{% url url_novo_voto votacao.id %}" method="post">{% csrf_token %}
                        <input type="hidden" name="id_restaurante" value="{{ cardapio.restaurante.id }}">
                        <input type="text" name="nome" class="input-small" placeholder="Seu nome...">
                        <p><button type="submit" class="btn btn-primary">Votar</button></p>
                    </form>
                </td>
              </tr>
         {% endfor %}
       </table>
       
		<div style="text-align:right;margin-top:80px;">
			<a href="{% url url_votacao_resumo votacao.id %}" class="btn btn-primary">Resumo da votação</a>
		</div>
 
    </section>	


{% endblock corpo %}

{% block javascript %}
{% endblock javascript %}

django/votacao/templates/votacao/resumovotacao.html
{% extends 'base.html' %}

{% block chamada %}VOTACAO{% endblock %}

{% block corpo %}

    <section id="global">
        
        <table class="table table-striped">
            <caption>Votações</caption>
            <thead>
                <tr>
					<th>Restaurante</th>
                    <th>Nome</th>
                </tr>
            </thead>
            <tbody>
            {% for voto in object_list %}
                <tr>
					<td>{{ voto.restaurante}}</td>
                    <td>{{ voto.votos }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>


 
    </section>	


{% endblock corpo %}

{% block javascript %}
{% endblock javascript %}

django/votacao/templates/votacao/sobre.html
{% extends 'base.html' %}
{% load static %}

{% block chamada %}VOTACAO{% endblock %}

{% block corpo %}

    <div class="row">
      <div class="span3 bs-docs-sidebar">
        <ul class="nav nav-list bs-docs-sidenav">
          <li><a href="#contexto"><i class="icon-chevron-right"></i> Contexto</a></li>
          <li><a href="#cardapio"><i class="icon-chevron-right"></i> Cardápio do dia</a></li>
          <li><a href="#contribuindo"><i class="icon-chevron-right"></i> Contribuindo</a></li>
          <li><a href="#creditos"><i class="icon-chevron-right"></i> Créditos</a></li>
        </ul>
      </div>
      
      <div class="span9">
        
        <section id="contexto">
            
            <div class="page-header">
                <h1>Contexto</h1>
            </div>

            <p>Ao sair para almoçar, temos que entrar na discução de <strong>onde ir</strong>.</p>
            <img src="{% static 'img/cardapiododia_sobre1.png' %}" width="380" /> 
          
            <p>Varias opções acabam surgindo, alguns gostam de um determinado local, outros não...</p>
            <img src="{% static 'img/cardapiododia_sobre2.png' %}" width="380" />
            
            <p>E até decidir por um local onde todos concordam, acaba-se levando um bom tempo!</p>
            <img src="{% static 'img/cardapiododia_sobre3.png' %}" width="380" />
            
            <p>Para piorar a situação, sempre tem alguém que não gosta da opção escolhida</p>
            <img src="{% static 'img/cardapiododia_sobre4.png' %}" width="280" />            
            <br/><br/><br/><br/>
        </section> 
        

        <section id="cardapio">
          <div class="page-header">
            <h1>Cardápio do dia</h1>
          </div>

          <p>Para diminuir o tempo perdido com a discução de onde ir almoçar, o cardápio do dia proporciona
             uma votação simples e antecipada. Onde é possível ver as opções de cardápios <small>(e preços)</small>
             dos restaurantes conforme o dia da semana.</p>
             
          <img src="{% static 'img/cardapiododia_sobre5.png' %}" width="280" />
          
          <p>E momentos antes do horário do almoço, é possível saber onde foi o local mais votado, e permitindo quem
             não gostou da opção, não participar do almoço naquele dia.</p>
             
          <img src="{% static 'img/cardapiododia_sobre6.png' %}" width="280" />
          <br/><br/><br/><br/>
        </section>
        
        
        <section id="contribuindo">
          <div class="page-header">
            <h1>Contribuindo <small>com o Cardápio do dia</small></h1>
          </div>

          <h4>Gostou do projeto?</h4>

            <p><a href="https://github.com/huogerac/cardapiododia/star">Marque </a>
               ou faça um <a href="https://github.com/huogerac/cardapiododia/fork_select">fork</a> do projeto no github.
            </p>
        
          <h4>Colabore com o projeto:</h4>
          <p>Reportar           <a href="https://github.com/huogerac/cardapiododia/issues?labels=question%2CBug&page=1&state=open">bugs</a></p>
		  <p>Sugestões ou novas <a href="https://github.com/huogerac/cardapiododia/issues?labels=question%2CIdeia&page=1&state=open">ideias</a></p>
          <br/><br/><br/><br/>
        </section>
        
        <section id="creditos">
          <div class="page-header">
            <h1>Créditos</h1>
          </div>

          <p>Roger Camargo</p>
          <p>Guilherme Gambeti</p>
          <p>Rogério Avelino</p>
          <br/><br/><br/><br/>
            
        </section>
       
        
        
  




{% endblock corpo %}

{% block javascript %}

{% endblock javascript %}